### ISSUE TITLE
Icons get duplicated while Iconscaling is not 1.

### ISSUE THREAD

**Issue by Koalahund** [theripper93/Levels#10]
Foundry version 0.8.6
Pathfinder1 0.78.9

Token icon settings:
![40844dc3e891af1a3fa11916a815c20c](https://user-images.githubusercontent.com/85458282/121791546-2d23b500-cbeb-11eb-8d51-612d1576efb7.png)

Moving a token while a player has his token selected and scale is not set to "1" works fine:
![a7c7af0226da2faa58582b0a75cdfeba](https://user-images.githubusercontent.com/85458282/121791525-f51c7200-cbea-11eb-9fa0-67c7e025469d.png)

Moving a token while a player has no token selected and scale is not set to "1" duplicates the icon. One icon exists with the scaleratio and 1 exists with scale set to 1 underneath the other token:
![d9c22d13a98d6d3eff839fd4ce639d76](https://user-images.githubusercontent.com/85458282/121791545-2432e380-cbeb-11eb-8aa8-80c437e1e031.png)

looks fine in gm vision
problem only occurs for players

**Comment by theripper93** [comment]
only for scale? is width and height fine?

**Comment by Koalahund** [comment]
> only for scale? is width and height fine?

yes

**Comment by theripper93** [comment]
should have located the issue, thanks - fix coming let me know if it's fine now
