### ISSUE TITLE
Measmurements are not displayed for players

### ISSUE THREAD

**Issue by aFKabi** [theripper93/Levels#100]
I have enabled only levels, and even when a map has no levels set my players cannot see measurements drawn on the map.

I created a new map, didn't add roof, or anything, it was just an image background in a basic new map.
I drew a circle with Measurement Controls.
The players cannot see the circle, but I can as a GM.
My View
![imagen](https://user-images.githubusercontent.com/2872646/188299110-65b729fa-73e6-4867-9a88-179c7cc512e1.png)
Player View
![imagen](https://user-images.githubusercontent.com/2872646/188299118-325db0e7-5ca9-4bbe-bc35-08f088cd1ebd.png)

**Comment by theripper93** [comment]
i cannot reproduce this, make sure to follow this https://theripper93.com/#/faq/troubleshooting and report back. Feel free to reopen the issue if you have more informations

**Comment by aFKabi** [comment]
> i cannot reproduce this, make sure to follow this https://theripper93.com/#/faq/troubleshooting and report back. Feel free to reopen the issue if you have more informations

I tried the entire troubleshooting steps and the issue is still present. I will write down detailed steps maybe this can help find the issue:

System: V10, 5e, latest version for both
If I only enable levels without dependencies, the issue does not happen.
But if I have Levels, + Wall Heights+ LibWrapper which are marked as dependencies for levels, the issue does happen.

This can be done if you login as a player through browser or the Foundry app itself.

1) Login as a player
2) Click Measurement Controls
3) Draw a circle in the field of view of the player

If its drawn outside the FOV of the player, the circle will be created properly, but if the player then gets it in their field of view, and presses the measmurement controls button, they will lose sight of said areas once again.


I do not see any errors in the console which I would assume means there is some issue when calculating FOV for the areas with walls+levels enabled.

**Comment by aFKabi** [comment]
@theripper93 I have no way to reopen this, but let me know if you need more information, like settings and so on.

**Comment by aFKabi** [comment]
After the latest update the issue does not happen anymore
