### ISSUE TITLE
Inconsistencies with light on different levels

### ISSUE THREAD

**Issue by Scimitri** [theripper93/Levels#101]
Issue occurred after the transition to v10.
Light placed on a higher floor (Floor 1) will be displayed as normal, but when you go to a lower floor ( floor 0) the lights from floor 1 will still be visible in UI mode. They will also only follow walls placed on floor 1.

Further, if perfect vision is installed, the lights on floor0 will be wholly blocked by the tiles itself placed on floor 1.

See images for setup of floor 1/0

![image](https://user-images.githubusercontent.com/28387521/188306259-49029eb8-1133-4963-8619-19c0a4b2892f.png)
![image](https://user-images.githubusercontent.com/28387521/188306269-3580805d-85cc-4adb-980b-0516e69d517c.png)

**Comment by theripper93** [comment]
fixed
