### ISSUE TITLE
Roof, Token Vision doesn't work when a token is elevated (works ok @ elevation 0)

### ISSUE THREAD

**Issue by TogaParty** [theripper93/Levels#106]
When configured to show token vision, a token should be able to see into a room through open windows or doors, and should see the roof tile for areas that are not visible.  This works as expected if the token has an elevation of zero, but doesn't work if the token is raised, e.g. elevation set to 10.  In the latter case the roof tile is still visible and blocks token vision, even though the token is under the roof.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
