### ISSUE TITLE
Option to hide Levels layer in the toolbar

### ISSUE THREAD

**Issue by apoapostolov** [theripper93/Levels#108]
I only use Levels as a requirement dependency for other mods, and due to many mods my toolbar is very cluttered. I am really looking for ways to cut down the number of icons there, so please add an option for Levels to hide its layer in the toolbar, off by default.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
