### ISSUE TITLE
Change "Strict Range" setting into "Show tile from above"

### ISSUE THREAD

**Issue by manuelVo** [theripper93/Levels#109]
I'd like to propose to change the "Strict Range" setting into a "Show tile from above" setting. Currently, when both the "Show even when below" and the "Strict Range" options are enabled, the tile will be invisible for tokens below. If enabled, the "Strict Range" option effectively overrides the "Show tile from above" option.

This limits the configuration options for tiles to the following three:
- Tiles that are only visible if the token is within the tiles' elevation boundaries
- Tiles that are visible to tokens within the tiles' elevation boundaries and tokens above
- Tiles that are visible to tokens all tokens, no matter if they are within the boundaries, above or below

By replacing the "Strict Range" setting with a "Show tile from above" setting, that works identical to the "Show even when below" setting - except for tokens above the range, instead of for tokens below, the configuration possibilities could be expanded by an additional tile configuration:
- Tiles that are only visible to tokens within the tile's boundaries and tokens below, but that are always invisible for tokens above.

Additionally, the "Show tile from above" setting could offer a "Max Elevation Difference" option like the "Show even when below" setting, to offer even more flexibility.

Reworking the setting as proposed, won't lose the functionality that the "Strict Range" setting was providing. Simply deactivating both "show from above" and "show from below" will achieve the same effect.

**Comment by theripper93** [comment]
Honestly while it might be interesting , the migration, the extra possible user confusion are not worth a feature that honestly no one ever asked for nor I see any obvious application for. Lately I’ve been very strict in new features unless extremely necessary. Can you provide a real use case example that is not extremely edge case where this could apply and that cannot be solved by other means?

**Comment by manuelVo** [comment]
I have a warehouse, which has wooden walkways that span over the main storage area. The walkway is implemented as a separate level. This is the view of the warehouse when standing on the walkway.

![combined_warehouse_upper](https://user-images.githubusercontent.com/1705157/198018132-3aca9060-2e20-4692-8420-2c2c77f6a953.png)

When Players are below, in the storage area, I still want them to still be able to tell where the walkway is, while giving them a good view on the things below. To facilitate this, I've built an overhead-layer for the lower level. It contains the beams that hold the walkway up, but not the walkway itself. This allows players to see the lower layer, while still being aware of the location of the walkway.

![combined_warehouse_overhead](https://user-images.githubusercontent.com/1705157/198018908-a09dc33c-40af-4f58-991f-bed6caf979aa.png)

This is the catch: The overhead layer and the walkway layer don't blend together very well. The overlay layer peeks out from under the walkway layer in several areas in ways that don't look very nice. For that reason, I'd like to only show the overlay layer to the players when they are below the walkway and want to have the overlay layer hidden once the walkway is shown.

**Comment by theripper93** [comment]
Honestly this definitely looks like a very edge case, the simple solution is to just shrink the beams or enlarge the walkway by a small amount . Sorry but I’m not making changes that would potentially require migrations at this stage of the module for such a specific issue that can be solved by other means
