### ISSUE TITLE
Blood not sticking to scene

### ISSUE THREAD

**Issue by Andrew226** [theripper93/Levels#110]
Is there anyway I can make blood splatters bind to the scene so when I change scenes it stays or so I can pre setup a scene where battle had already happened and have blood be present for the effect?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
