### ISSUE TITLE
Player Portraits/Avatars not appearing for GM

### ISSUE THREAD

**Issue by JamesBorg** [theripper93/Levels#114]
**ALL OTHER MODULES DISABLED?** true
**Module:** Smart Target 0.9.7
**Foundry and System version**: Foundry 20.290 DnD5e 2.0.3
**OS, Hosting, Browser (if applicable)**: Hosting - AWS t2.micro, Client - Ubuntu 22.04 Chrome 105.0.5195.125 
**Short Description of bug**:
Player tokens not appearing when players are targeting.
**Screenshots and/or console errors**:
![image](https://user-images.githubusercontent.com/56056503/201509024-7b8be7a9-c22d-4e3d-841e-5883112baff7.png)
![image](https://user-images.githubusercontent.com/56056503/201508979-53187a79-5187-4abb-a2f5-422f8239c3c9.png)
Left is logged in as Player, right is logged in as GM

**Comment by theripper93** [comment]
Can you reopen this issue in the smart target repo please
