### ISSUE TITLE
Creating a token while another token is selected throws an error in console

### ISSUE THREAD

**Issue by Koalahund** [theripper93/Levels#12]
Versions:
0.8.6 foundry
0.78.9 PF1
levels 0.5.8
libWrapper 1.7.0.0
Better Roofs 0.8

Creating a token while another token is selected throws an error in console, don't see anything that doesn't work caused by this but maybe you still want to fix that :D

![0551a5c275a7f2c119b6b63d83a31c1c](https://user-images.githubusercontent.com/85458282/121821562-0ff9ef80-cc9a-11eb-8f39-15a17a5686ad.png)

**Comment by Koalahund** [comment]
only seems to happen when the selected token has vision enabled

**Comment by theripper93** [comment]
i cannot seem to reproduce that error, but it seems the icon for the token doesen't exist for some reason. It's nothing terrible and i prefer to not just put an ignore on the issue if it's actually a problem of some kind, if i manage to reproduce it i will fix it. Does it happen with other modules disabled?

**Comment by Koalahund** [comment]
ok tested some more

only module enabled: levels
still get the error

steps to reproduce
1. drop a new token on the map, can have vision or not, doesn't matter
2. select the token
3. drop another token onto the canvas that has vision ENABLED in the prototype token settings
4. error

**Comment by theripper93** [comment]
Ok, i manage to reproduce it, i think what's happening is that particular circumstance, for some reason, when that function is fired the token icon(image) has not been loaded yet - i'm just gonna put an ignore on the error i guess
