### ISSUE TITLE
Cannot create levels within new world.

### ISSUE THREAD

**Issue by adamrusted** [theripper93/Levels#120]
Hi there - I've done a fresh install of Foundry 10.288 and have installed Levels, libWrapper, and Wall Height.
The Levels UI shows up as anticipated, including tooltips, but I'm not able to actually add/edit the levels within a scene.
I'm not seeing any errors in the console, and I can set properties on tiles etc as expected - but not able to actually set up individual levels. Happy to provide further system details if needed.

**Comment by theripper93** [comment]
Update foundry to latest 291 or downgrade levels to 3.6
