### ISSUE TITLE
Show items spanning multiple levels on any level they contain

### ISSUE THREAD

**Issue by DawidIzydor** [theripper93/Levels#121]
Sometimes it is usefull to have an item spanning multiple levels, eg. let's say I have a guard tower with a light on the 1st floor (spanning 10-19 fts), and I want that light to iluminate both 1st floor and the ground floor (so I set it up from 0 to 19 ft). The logc works fine and the light iluminates both areas, however the light icon is not visible when viewing any floor - to see it I must close the layer tool altogether. Another use case is for walls spanning multiple levels, instead of duplicating them on every level it is easier to set them up spanning all the floors - but they are not visible when using the layer tool.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
