### ISSUE TITLE
[Suggestion] Fog of war reveal blocking and holes

### ISSUE THREAD

**Issue by SirAron111** [theripper93/Levels#122]
So i real love this module, but I have a few issues with it when using simple layered maps.
The first one would be that if I use maps for the layers which do not have transparent parts, be it because they are jpgs to reduce data or simply portray the lower floors on the upper floors art as well. There is no "Hole" function. Would it be possible to add a feature to drawings or so that if I draw a section like a cut-out on the same elevation as the tile i am on, that i could have tokens on that elevation or below that elevation see through the tile on that constrained location. So i don't need to duplicate and copy all tokens during combats or so if they shift to places where it would be logical to see them from above etc. I believe a different module once had such a function which worked well with lvls, but not anymore. Would be nice if i could select on drawings not just stairs and elevators, but also holes.

The second one would be about the advanced fog of war. Is there a way to "block the fog of war revealing" while on a higher tile in lvls? Because when my players explore a floor above, the advanced fog of war neatly makes it so that they basically don't reveal anything there with exploring fog, but once they get to the lowest tile, the background layer, that dungeon floor was basically fully revealed since they traveled through the upper floors and there passively revealed the fog of war.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
