### ISSUE TITLE
3.2.25 to 3.3.5 Did not provide module manifest data

### ISSUE THREAD

**Issue by MrTranscended** [theripper93/Levels#124]
When updating Levels from 3.2.25 to 3.3.5, I'm getting an error that states:

The requested manifest at "https://github.com/theripper93/Levels/releases/latest/download/module.json" did not provide module manifest data.
![error](https://user-images.githubusercontent.com/74849518/214676811-296f7ae0-4770-40d8-9b94-ecb09f5ec114.png)

**Comment by theripper93** [comment]
Sometimes github will timeout download request, try again later, it's not a Levels specific issue
