### ISSUE TITLE
[Request] Make Discovery modes available behind canvas?

### ISSUE THREAD

**Issue by KJTailor** [theripper93/Levels#126]
Hi Ripper,

I noticed the  other day that a PC with "tremorsense" can't "see" enemy tokens.

Investigations revealed that on that particular map, the issue was, that the map background for this scene needed to have elevation -80 (basement level with different depths), which makes tremorsense dysfunctional.

Would it be a possibility to link levels to detections modes, in a way of linking background elevation so that it let's the game know they should work, depending on the background elevation, rather than set with standard elevation zero?

thanks

**Comment by theripper93** [comment]
No, detection modes are system specific, they should check the background elevation instead of using a flat 0, that information is availeble even without levels
