### ISSUE TITLE
Hearing detection mod don't working

### ISSUE THREAD

**Issue by Eserg14BB** [theripper93/Levels#127]
"Hearing" token detection mode does not work if the "Levels" module is enabled
Tested on Pathinder 2 system

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
