### ISSUE TITLE
[BUG] The module clashes with MATT and removes the content of the Levels tab on all tiles.

### ISSUE THREAD

**Issue by TheXeno30** [theripper93/Levels#129]
Describe the bug
The module clashes with MATT and removes the content of the Levels tab on all tiles.

To Reproduce
open any tiles.

Expected behavior
in the Levels tab there should be setting to adjust sight and hight

Screenshots
![image](https://github.com/theripper93/Levels/assets/135822719/0658f335-ed06-4853-89ee-dbef1acde966)

Please complete as much of the following information as possible:

Browser Chrome
Foundry Version 10.291
System Cyberpunk RED - CORE v0.86.1
module version 10.21
![image](https://github.com/theripper93/Levels/assets/135822719/5e9eb2cd-67fb-4972-bac4-f18a110a21a0)

Used "find the culprit" it to find that active tiles and Levels clash

**Comment by theripper93** [comment]
This was broken due to a change in MATT - i've slapped a fix in the V11 version of levels, if you are on V10 downgrade MATT

**Comment by TheXeno30** [comment]
just posted a comment with MATT and he/they responded with Levels putte the tab in the wrong place. Its a bit above my paygrade, since in not a programmer, so i don't know how this works, but maybe a solution can be reach between you, for all us v10 users (I can't be the only one running v10 still and using both your awesome modules.). 
I'm on forge, so downgrading i dont know how to do.

Thanks again for the time.

**Comment by theripper93** [comment]
Again, I’ve added a fix for this in v11 but the v10 version is no longer supported

**Comment by theripper93** [comment]
Just to be clear, I’m not saying it’s a MATT issue, I’m saying the v10 version will not get this fix
