### ISSUE TITLE
Incorect light calculation with light sources that have an height maximum in all V11 stable versions

### ISSUE THREAD

**Issue by R0TEAM** [theripper93/Levels#132]
Actual Foundry V11.302

Modules : 
Better Roofs 1.9.2
DF Active Lights 1.3.1
Levels 4.1
lib - color settings 2.9.1
libwrapper 1.12.12.1
math.js 7.5.1 -fvt2
The Ripper93's module hub 1.1
Wall Height 5.0.1

have created light sources with height (top) 10 and height (down) -infinity
any token (NPC or player) that have an height greater than 10 (token height + token vision height)
dont calculate the light sorce aka -> black, no sight from light
Have worked nice in Foundry V10.x, or if i disable Levels in V11 (even NO Level at all is created in the scene)

**Comment by theripper93** [comment]
Due to changes in V11 APIs this behaviour is expected and you won't be able to get the old v10 behaviour, see https://wiki.theripper93.com/levels#light-masking
