### ISSUE TITLE
All Drawings Hidden And Inaccessible When Not Controlling Token

### ISSUE THREAD

**Issue by Deiviux90** [theripper93/Levels#133]
With Levels enabled, I can't draw anything without having it become hidden from GM view. Drawings are only visible after selecting a token, but then they aren't editable, which I need to do in order to combine the Levels module with the Multilevel module

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
