### ISSUE TITLE
South/north movement breaks after using an elevator [V11]

### ISSUE THREAD

**Issue by Essylo** [theripper93/Levels#134]
Token movement using arrows behaves weirdly after interacting with an elevator whether or not the token changed elevation.

Moving left and right works normally but up and down makes the token move diagonaly to the right. All other tokens you select after that are affected too. Clicking out of the foundry window solves it.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
