### ISSUE TITLE
Issue with Token Vision when level is running

### ISSUE THREAD

**Issue by gris-x** [theripper93/Levels#135]
When level is running, and token vision is checked on the scene, clicking on a token with a set vision causes the game to freeze.
it is then impossible to pan the map, or see other tokens or get the vision from that token.
long left clicking on the map takes a few seconds but it "resets" the panning.
All these issues go away when either
1/ you uncheck the Token vision on the scene
2/ you disable the level module

Foundry V11 latest build ..06
Chrome

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
