### ISSUE TITLE
Levels Having problems with lights

### ISSUE THREAD

**Issue by stevenagl12** [theripper93/Levels#138]
Hi, I am having an issue with the levels module where I put lights on the next level up and for some reason they are illuminating in the general area of the lower floors walls, even though, said walls are not placed on the current floor.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
