### ISSUE TITLE
[Feature Request] Only show lights for the current floor

### ISSUE THREAD

**Issue by Bolt7** [theripper93/Levels#14]
I'm guessing that the Levels navigator GUI is supposed to only show lights for the level you're on, just as it only shows the level's walls, drawings and tiles. While it only shows the floor's lights' icons, the light itself is always shown for all floors.

Steps to replicate:
- Have a building with multiple levels set up
- Put lights on multiple floors
- Activate the "Enable Levels View/Placement" toggle
- Note that you can see the light of all floors instead of just for the floors you're on

**Comment by theripper93** [comment]
yes, that's not a "bug", it's more that i haven't added that feature in yet

**Comment by Bolt7** [comment]
Got it, changed the title. Thanks!

**Comment by theripper93** [comment]
The feature was added in the latest release

**Comment by Bolt7** [comment]
Wow. Now I get why the issues tab was empty. Thanks for being so quick!

**Comment by theripper93** [comment]
;)
