### ISSUE TITLE
Compatibility problem and license question

### ISSUE THREAD

**Issue by Saibot393** [theripper93/Levels#140]
I have found a compatibility issue between Levels and one of my module. I think i can fix it, but i will have to copy and modify a few of levels functions to do that. Since i can not find any mention of a license in this repository i wanted to ask for your permission to use some of levels code in a modified way to fix this compatibility issue.

**Comment by theripper93** [comment]
You have permission to utilize levels code for that purpose, but I would incourage you not to to avoid creating issues to other modules that use the levels api. If it’s the only way tho, yes you can use parts of levels code if you need to do overrides, just specify so with a small comment in the code (as you realized levels is in fact not open source)

**Comment by Saibot393** [comment]
Thank you very much. Would troubleshooting-help be the right channel on your dicord to explain the issue?

**Comment by theripper93** [comment]
No this is a DM kind of situation
