### ISSUE TITLE
foundry v.10

### ISSUE THREAD

**Issue by DrouDrougar** [theripper93/Levels#141]
So is this compleatly unusable in version 10 of foundry? or are there some versions where it works? cause i would love to be able to use this but i don't really wana downgrade my foundry version to be able to use it.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
