### ISSUE TITLE
BUG: Levels breaks overhead feature when using Monk's Active Tile Triggers

### ISSUE THREAD

**Issue by Oryan77** [theripper93/Levels#142]
When I set a tile to overlhead and select "Occlusion Mode: None (Always Visible)", the tile image does not switch according to my Trigger inputs when a token lands on the tile. If the tile is not an overhead tile, the trigger works as expected (switches images). 

I ran Find the Culprit and determined that Levels is keeping the tile from working as expected with the Active Tile Trigger when set as an overhead tile.

Here are screenshots of the Triggers I used that don't work with Levels activated.

![image](https://github.com/theripper93/Levels/assets/49130820/0848bdd1-b9b4-4b4d-8f3c-0ea2767e5439)
![image](https://github.com/theripper93/Levels/assets/49130820/3b988cdf-1a2d-4394-bdaf-d3d5e7a314a6)
![image](https://github.com/theripper93/Levels/assets/49130820/364eed77-750f-4b0b-895b-851f5b26a763)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
