### ISSUE TITLE
Templates not working

### ISSUE THREAD

**Issue by strife98** [theripper93/Levels#144]
Unsure if this is Levels or Wall height issue, but making a template, and then dragging and dropping the template onto the map does not bring over the saved options. Copy/paste also does not bring over the same options. These options would be super helpful for tile mapmaking as manually changing the setting on each tile takes way too long.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
