### ISSUE TITLE
[Feature Request] Moving items between floors. 

### ISSUE THREAD

**Issue by strife98** [theripper93/Levels#145]
The ability to move an object from one floor to another without having to remove and replace the item would be great. Especially if you place the item without having the level tool open accidentally as you absentmindedly make a dungeon map and forget that you haven't selected the basement layer. Maybe something in the options like a drop down that you can set the item you've placed to one of the floors you have made.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
