### ISSUE TITLE
BUG: Levels breaks overhead feature when using Monk's Active Tile Triggers

### ISSUE THREAD

**Issue by Oryan77** [theripper93/Levels#146]
**I have disabled all other modules: **True
**Module(s) **Levels v4.2.7
**Conflicting Module(s) **Monk's Active Tile Triggers v11.17
**Foundry and System version **Foundry 11.315
**OS, Hosting, Browser (if applicable) **Windows 10, Firefox
**Short description of bug **Levels breaks overhead feature when using Monk's Active Tile Triggers
**Simple steps to reproduce the bug **

When I set a tile to overlhead and select "Occlusion Mode: None (Always Visible)", the tile image does not switch according to my Trigger inputs when a token lands on the tile. If the tile is not an overhead tile, the trigger works as expected (switches images).

I ran Find the Culprit and determined that Levels is keeping the tile from working as expected with the Active Tile Trigger when set as an overhead tile.

Here are screenshots of the Triggers I used that don't work with Levels activated.

**Screenshots and/or Console Errors**
![image](https://github.com/theripper93/Levels/assets/49130820/fe1e6ac3-32e5-4e5a-a1e0-ce59d7bcbb8b)
![image](https://github.com/theripper93/Levels/assets/49130820/b632006d-7e7a-49ee-a9fb-f7c72b064058)
![image](https://github.com/theripper93/Levels/assets/49130820/198ff968-6e68-4b8a-8be5-5d8692d7895d)

**Comment by theripper93** [comment]
This has nothing to do with levels , it’s how MATT built levels compatibility . All the moving token triggers require that the token is at the elevation of the overhead tile when levels is enabled. If you want this to be a toggle able option you’ll have to ask Matt, It’s not something I can change
