### ISSUE TITLE
bug: unable to select more than one spell target

### ISSUE THREAD

**Issue by ryanwolhuter** [theripper93/Levels#147]
First of all just want to say big props for this plugin. Our group and our DM love it.

We came across a bug while playing our last session:

When casting a spell that has multiple targets, I was unable to select any more targets than the first one.

I did confirm that I was in range to cast the spell on the targets.

I took a screen recording when I noticed the problem, see below.

Thanks for all your great work!

https://github.com/theripper93/Levels/assets/39741965/9e50b970-3e85-40b4-aaec-2081b938a04f

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
