### ISSUE TITLE
Opening/closing a door makes all notes visible regardless of current elevation in the layer tool

### ISSUE THREAD

**Issue by Truuun** [theripper93/Levels#148]
**I have disabled all other modules:** True
**Module(s)** Levels
**Conflicting Module(s)**
**Foundry and System version** Foundry 11.315, Pathfinder Second Edition 5.14.3
**OS, Hosting, Browser (if applicable)** Windows 11
**Short description of bug** Opening/closing a door makes all notes visible regardless of current elevation in the layer tool
**Simple steps to reproduce the bug**

1. Open the levels layer tool
2. Create two levels: one with elevation from 0 to 10, another with elevation from 10 to 20
3. Create a door at first level
4. Create a note at second level
5. Switch to level with the door
6. Open door
7. Observe the note from the second level suddenly appearing

**Screenshots and/or Console Errors**
![DoorSetup](https://github.com/theripper93/Levels/assets/7766914/7667a0a9-c726-4955-bd76-517f83ede182)

![NoteSetup](https://github.com/theripper93/Levels/assets/7766914/b6f8b0a1-0eb1-4c89-aeb8-2262f18aafd1)

![Level2](https://github.com/theripper93/Levels/assets/7766914/41d6f128-754c-4d6a-aa8a-9b12b8d9eafa)

![Level1](https://github.com/theripper93/Levels/assets/7766914/0e1a4f6a-27e2-466c-9d7d-4d441e456e0f)

![NoteAppears](https://github.com/theripper93/Levels/assets/7766914/ef82baa8-d309-455d-adac-5c1750122896)

**Comment by theripper93** [comment]
fixed
