### ISSUE TITLE
[Suggestion] Show Elevation on token hover option

### ISSUE THREAD

**Issue by SirAron111** [theripper93/Levels#149]
Hi, just wanted to ask if it is possible to add an option to the level's elevation hide and show selection that allows elevation to only show when hovering over a token. I like it when everyone can see the elevations, but it gets a bit cluttered when I have multi level maps with various tokens and all have the big fat numbers above them.

Here is an example of a map where i run a cloud giant castle in the sky and a bunch of chess golems with piled up numbers. Which would look better if the value only shows when hovered. Not sure if possible.
![Unbenannt](https://github.com/theripper93/Levels/assets/39855956/fd532d17-1337-4782-961e-3f23af51fd0b)
![Umnbenannt](https://github.com/theripper93/Levels/assets/39855956/6123b27c-30fc-4bb1-b1b9-dd4d04c1b629)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
