### ISSUE TITLE
Questions regarding elevators & info text

### ISSUE THREAD

**Issue by Edvinas01** [theripper93/Levels#150]
Hello,

I started using Foundry not too long ago and setup your Level plugin to aid in my Spelljammer themed campaign! So far I'm loving the module and can't wait to try it in next session. Putting each ship level in separate scenes is such a PITA >.>

I'm a bit confused though on how to use the Levels module to create "labels" which are only visible on certain levels and additionally am not fully sure I understand how elevators (or ladders in my case) work.

1. For example, I want to show the players a different label on each floor with some information related to that floor only. Is this possible or is there a workaround I could apply to hide the text from below levels when the players are above the text?

https://github.com/theripper93/Levels/assets/8227320/368ad02f-e9e6-44ea-801e-fbf18afd4544

2. I'm trying to create a elevator (ladder) which spans all 3 floors on my ship. I created an elevator on 0-9 level (ground, height) and it shows up on all levels but is only usable from level 0. To workaround this I've copy pasted the elevator on each level (elevator configs are 0-9, 10-19, 20-29), however the last elevator (20-29) starts acting in weird ways where if a player walks up to the elevator they get moved to level 30 automatically even if they don't interact with the popup.

https://github.com/theripper93/Levels/assets/8227320/dd953d12-286a-4e8f-adf8-a79d5f25a540

https://github.com/theripper93/Levels/assets/8227320/e1eb40e2-8ebd-45b8-a763-afc2d7c23d6e

_P.S. ignore lower level spanning from 0 to 9 in the videos, I was messing around and forgot to set it back to 10 during recording..._

Thanks,
Ed

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
