### ISSUE TITLE
Players with regular vision unable to see other tokens in scene.

### ISSUE THREAD

**Issue by donsuave** [theripper93/Levels#151]
With the update it seems that when levels is enabled, player tokens that don't have dark vision aren't able to see other tokens when vision is enabled, even in lighted areas.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
