### ISSUE TITLE
Issue loading some scenes

### ISSUE THREAD

**Issue by Issacar13** [theripper93/Levels#152]
I have the module version 5.0.9 and Foundry version 12. Some scenes are not loading when I have levels activated.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
