### ISSUE TITLE
API Help for macro

### ISSUE THREAD

**Issue by Azazel666** [theripper93/Levels#155]
Hi.

I love your module for levels, and I want to create a macro in my game that can make a token crouch. What I am attempting to create is a macro that toggles between the default token height and reducing it by half.

My problem is that I can not find a way to update the token height property on my token with code via a macro, so I would appreciate some guidance on an API function or how to update the token to set a custom height or reset it.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
