### ISSUE TITLE
[Bug] Vision not working across levels through transparent tile parts.

### ISSUE THREAD

**Issue by SirAron111** [theripper93/Levels#156]
Hi i am experiencing a strange behavior related to light not providing vision on tokens via the level's module on multilevel canvases. For some reason despite there being lights on the lower floor and the tile space of the upper floor having a large transparent part (png/webp) section that should show the lower floor to tokens with vision, the tokens can not see the tokens on the lower floor despite being able to see through the transparent part itself.

Currently using:
Foundry Version 12
Levels Version 5.2.9

Here is an example of what i mean. I have the Ogre selected, he has vision like any player token has. Darkvision 60 feet. Light perception infinite. But he can not perceive the tokens on the lower floor. The floor below has lights placed that even shine through to the top floor via the transparent part. Both the ogre token or any other token like, players can not see the tokens below.

![Unbenannt](https://github.com/user-attachments/assets/1816d1e8-20d8-4e7b-8688-1fa66f114f25)
![Unbenannt2](https://github.com/user-attachments/assets/0b602781-831c-4e3a-b150-1fb6fe340318)
![Unbenannt3](https://github.com/user-attachments/assets/d4fc45df-cf80-4e2e-aa99-e4d7f59d2714)

I figured out that if i go against the tooltip of the levels configuration options and set "levels: don't disable lights" to true, the vision works fine. 
![Unbenannt5](https://github.com/user-attachments/assets/498d4050-24db-43b7-976d-e4ebd7aec161)
![Unbenansffdnt](https://github.com/user-attachments/assets/ac18ca99-dcb3-40ee-ab70-865d2dafc895)

But than it give s me a warning icon in the levels menu?
![Unbenannnt](https://github.com/user-attachments/assets/40a5e5df-d2c9-423b-be32-370d708a617e)

Is this a bug? Is this intended? I can not find any documentation that explains why the setting causes this behavior when it messes with transparent tile parts and vision like this? Does it break other things if i have it turned to true?

I also learned that if i pump the Tokens darkvision up to 120 or more, so it surpasses the elevation of 100 feet (it's the upper floor of a giant forge) then the token can see the tokens below. Even if I don't set the setting to true. But does that mean that the light perception simply gets ignored in the recommended setting style?

**Comment by theripper93** [comment]
The don't disable lights has side effects that's why the warning, but you can have it on and ignore the warning for this map
