### ISSUE TITLE
Dragged Tokens Ignore Stairs

### ISSUE THREAD

**Issue by SaltSouls** [theripper93/Levels#158]
When dragging a token to a new location, if they pass over a staircase, they will not be made to go up or down to the next floor as they should be. This can allow players to completely bypass the levels system when in rooms with potentially large drops if the just drag their token past the designated drop zone.

**Comment by SaltSouls** [comment]
> Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.
> 
> If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.

I have updated the issue with all necessary information, and would like to request it be reopened as I am not able to reopen the issue without either you doing it, or creating an entirely new issue.

**Comment by theripper93** [comment]
After reviewing your issue, this is expected behavior - if you wish tokens to change elevation when passing use regions and the appropriate event. The issue will not be reopened
