### ISSUE TITLE
[BUG] Light that emits from a token leaks into a level below

### ISSUE THREAD

**Issue by Zimnior12** [theripper93/Levels#159]
**I have disabled all other modules:** True
**Module(s)**
levels 5.3.8
**Conflicting Module(s)**
**Foundry and System version**
Foundry v12 331 D&D 3.3.1
**OS, Hosting, Browser (if applicable)**
Win 11, Linux, Tested on Chrome and VTTDesktop Client (by TheRipper93)
**Short description of bug**
Light that emits from a token leaks into a level below.
**Simple steps to reproduce the bug**

1. Edit a token and make it emit light
2. Check level below

**Screenshots and/or Console Errors**

https://github.com/user-attachments/assets/8101f4ad-0ccb-4a80-9efb-a58f6a27f327

**Comment by theripper93** [comment]
Does it leak if you have a token selected in the lower floor? or is it just a GM issue?

**Comment by Zimnior12** [comment]
It's just a GM issue. If you have a token selected on the floor below it works fine.
