### ISSUE TITLE
[Improvement] Hide Set Elevation for next placed template button from players.

### ISSUE THREAD

**Issue by Grandsome** [theripper93/Levels#161]
![image](https://github.com/user-attachments/assets/da1c4f2b-b2e3-46e0-9bb0-7d4dc08d327c)
To Declutter the player side of UI.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
