### ISSUE TITLE
Some conficts levels and midiqol  

### ISSUE THREAD

**Issue by SATANYASHA2017** [theripper93/Levels#19]
![image](https://user-images.githubusercontent.com/86288543/122886189-8b763380-d361-11eb-8d33-3137655319aa.png)
![Безымянный](https://user-images.githubusercontent.com/86288543/122886296-a8126b80-d361-11eb-9b89-b347ec380029.png)
![image](https://user-images.githubusercontent.com/86288543/122886349-b496c400-d361-11eb-958e-457d0a613795.png)
![image](https://user-images.githubusercontent.com/86288543/122886414-c37d7680-d361-11eb-85a2-12e98e227150.png)

**Comment by SATANYASHA2017** [comment]
![image](https://user-images.githubusercontent.com/86288543/122888397-a8136b00-d363-11eb-9775-19fe47e51f92.png)
it made this i think xD 
Cant even click

**Comment by SATANYASHA2017** [comment]
> ![image](https://user-images.githubusercontent.com/86288543/122888397-a8136b00-d363-11eb-9775-19fe47e51f92.png)
> it made this i think xD
> Cant even click

Nope. I reloaded and side bar seems working as usual. Still searching for this conflict

**Comment by theripper93** [comment]
this midi setting is the reason for the conflict. 
![image](https://user-images.githubusercontent.com/1346839/122914238-b8731800-d35a-11eb-8a80-0fdbb9d68c56.png)

gonna close the issue and add a warinig on the repo
