### ISSUE TITLE
Changeing token heigth freezes movement

### ISSUE THREAD

**Issue by Nordiii** [theripper93/Levels#2]
While doing some testing if I could get something to work with dungeondraft and levels i noticed that when I change my token heigth I cant move my token anymore.

As soon as i moved the secene a little bit the token could be moved again.

**Foundry:** 0.8.6
**System:** DnD5e 1.3.3
**Server OS:** Pi Buster (Debian)
**Browser:** Firefox
**Modules:** Better Roofs, Levels, libWrapper, Multilevel Tokens, Universal Battlemap Imprter

**Comment by theripper93** [comment]
does this happen consistently? i don't see why that would happen, have you tryed without MLT and UBI?. I don't seem to have this issue on my end

**Comment by Nordiii** [comment]
Yes, it happens always when I change the Token height via the Token HUD.

Currently not at home so I can’t verify with my test instance, will do it later.

**Comment by Nordiii** [comment]
So, I retested this and it seems that this is default Foundry behavior.

When you enter a number and hit enter in any input field the token can’t be moved until clicked somewhere.

I guess this can be closed then? 

Sorry for not properly validating this before.

**Comment by theripper93** [comment]
no worries glad it's not a bug :P
