### ISSUE TITLE
Incompatibility between Levels and Hex Size Support

### ISSUE THREAD

**Issue by dirusulixes** [theripper93/Levels#21]
Cross-referencing here from: Ourobor/Hex-Size-Support#17

fvtt 0.8.8
Hex Size Support 1.1.10
Levels 0.9.7.3 (and required dependencies)

With Levels enabled the box around tokens of size greater than one is square. 

with Levels:
![image](https://user-images.githubusercontent.com/5693623/123523246-60217a80-d6ba-11eb-9fb9-8ed23581cb6a.png)
without Levels:
![image](https://user-images.githubusercontent.com/5693623/123523266-7deedf80-d6ba-11eb-98e3-31e454479f33.png)
No errors in console

**Comment by theripper93** [comment]
closed as it's been woked on by the other developer

**Comment by dirusulixes** [comment]
I can't say if it's a recent change in Levels that caused it, but it seems the issue is gone
![image](https://user-images.githubusercontent.com/5693623/128229574-1d24f027-2183-46c2-bd7a-96ad8b64f7d7.png)

**Comment by theripper93** [comment]
oh i swapped the token refresh to wrapper instead of override for increased module compatibility ;)
