### ISSUE TITLE
Does Not Properly Handle Fractional Elevations

### ISSUE THREAD

**Issue by tjlanza** [theripper93/Levels#22]
**Foundry VTT 0.8.8, Levels 0.9.6, Better Roofs 0.9.2, Wall Height 3.5.3.8**

![image](https://user-images.githubusercontent.com/21128724/123560291-56a61a00-d76f-11eb-8828-a41326c34d0f.png)

When using the automated function to generate stairs, the module does not accurately reflect the level bands created in the UI. For example, using the above configuration, creating a stairway via the drawing tool configures "Height (Top)" to 2.9 and "Height (Bottom)" to 0. "Text Label", however, is set to "Levels Stair 0-3.9". When a token enters the region, the altitude is changed to 3.9, accurately reflecting what the label indicates, but not reflecting the base elevation of the next floor up.

The expected behavior would be for both the text label and the elevation change to take into account the base elevation of the next floor up. Instead, it appears to be referencing the top of the current level and simply adding a flat one to the value.

If one is working with feet (as a game like D&D does), integer ranges make sense. 0-9 is a reasonable level band both in the real world and for game purposes. A static bump of 1 unit between level bands is functional and appropriate.

However, not all games operate in US/Imperial units. For a game operating in metric, three meters between floors offers the same real-world and game-purpose level band. The module should be able to handle the distinction with the same ease it does for foot-based measurements.

**Comment by theripper93** [comment]
fixed
