### ISSUE TITLE
Vision is calculated incorrectly in scenes that have levels with negative elevation

### ISSUE THREAD

**Issue by manuelVo** [theripper93/Levels#23]
The following image stems from a scene that has two levels. One ranging from -10 to -1 and one ranging from 0 to 9. Each level has one wall. The wall on the left is on the upper level, as is the token. But as you can see the wall isn't being rendered.

![grafik](https://user-images.githubusercontent.com/1705157/124384149-442c6300-dcd0-11eb-8f8a-5dc3683a596d.png)

Digging a little deeper: For some reason, `game.currentTokenHeight` (which is set by wall height) reports `11` instead of `5`, but only if Levels is enabled. If levels is disabled the vision is calculated correctly.

[This is the world that the bug is appearing in](https://github.com/theripper93/Levels/files/6759841/lichtgeschwindigkeit.tar.gz)

FoundryVTT version 0.8.8
Installed modules:
```
_dev-mode 1.1.4
betterroofs 0.9.3.5
levels 1.1.2
lib-wrapper 1.7.3.0
wall-height 3.5.3.9
```

**Comment by theripper93** [comment]
this is not a bug but expected behaviour, Levels calculates sight from the eyes of the token wich are at +6 feet by default, you can change this in the settings
