### ISSUE TITLE
[Request] Move between levels when enter/leave polygon

### ISSUE THREAD

**Issue by PalaNolho** [theripper93/Levels#24]
I have this case where I want players to be able to move on top of environment elements (like boulders, crates, etc...) in an easy way. With stairs it's weird because, the system will only move between the levels if the centre of the token ands inside the polygon (which means that in most cases we need to keep with stairs that occupy full tiles) but then you can only leave to the other floor again once you move outside the stair and move back in.

What I like to suggest would be to add a mode (or maybe extend the stairs functionality?) to allow to trigger the movement between floors once the player enters or leaves the polygon.

See example:
![image](https://user-images.githubusercontent.com/6009914/124586444-56341000-de4e-11eb-8525-1c5546a181d3.png)

- in this case, when the player climbs the bolder and enter the polygon he would immediately be on the the upper level
- and then it move out of the polygon he would would be climbing down so he would immediately go back to the ground level

Hope it makes sense :)

**Comment by theripper93** [comment]
Stairs are there for basic functionality, to do what you want you can just use an MLT macro
