### ISSUE TITLE
[Bug] Disappearing and distorted tokens

### ISSUE THREAD

**Issue by odhinn33** [theripper93/Levels#27]
Disabled all modules except: Levels, Better Roof, Wall Height and libWrapper.
I posted here but could be some of these modules problem.
- I didn't set any Levels on scene.
- All tokens are 0 height
- No overhead on scene
Weird behaviour from token views, some disappear, some not... expecially with distorted horse-tokens (Width-unit:1 Height unit:1 Scale:2.6)

https://user-images.githubusercontent.com/62665887/124677343-89af8280-dec0-11eb-8370-466e99427c8c.mp4

**Comment by theripper93** [comment]
i'm working on the distorted token issue (still trying to find out what's happening there) about the disappearing token can you give me more information on vision settings\walls\lighting?

**Comment by odhinn33** [comment]
Yeah, sure:
- No walls in the scene
- "The Lady" token vision:
![Trianna_vision](https://user-images.githubusercontent.com/62665887/124677948-cb8cf880-dec1-11eb-96c8-274d44b0caad.PNG)
- Light on scene seems causing the distortion as if I turn it off, they only disappear and not distort. But it happened in another scene without light... I attach the "fact".
![Cattura2](https://user-images.githubusercontent.com/62665887/124678384-b19fe580-dec2-11eb-814b-14528ce32714.PNG)
![Immagine_2021-06-24_215244](https://user-images.githubusercontent.com/62665887/124678413-bf556b00-dec2-11eb-9cb2-145e9a92273c.jpg)

**Comment by theripper93** [comment]
ok, i seem to have figured out the distortion, update and check if it's solved. is there unrestricted vision range in the map?

**Comment by odhinn33** [comment]
Hey, it seems you did it! Good job man!
No unrestricted vision range in the map. Everything is off in "Vision & Lighting" configuration.
I'll keep you updated if it will ever happen again. Thank you.

**Comment by theripper93** [comment]
i think your tokens disappear because without unrestricted vision range and 0 sight you don't see shit xD

**Comment by odhinn33** [comment]
Ok, I turned ON _unrestricted vision range_ but disappearing tokens are still there...
In this case, I have a player controlling 2 tokens:

https://user-images.githubusercontent.com/62665887/124799650-13a92b00-df55-11eb-9347-cccc30d0dc86.mp4

**Comment by theripper93** [comment]
that ooks to me that your token just does not have vision - pop into the discord and ping me there if the issue persists i need to take a look via screenshare
