### ISSUE TITLE
Token elevation doesn't work properly while moving via measured path (ctrl+click > spacebar)

### ISSUE THREAD

**Issue by Riosodu** [theripper93/Levels#29]
**Addons:**
**_Levels 1.2.1
Better Roofs 0.9.3.6
LibWrapper 1.7.5.0
Wall Height 3.5.3.8_**

Not sure if this is a bug or a system limitation, however I feel this need to be informed. 
While moving via measured path, the elevation will only change if one point of the path is on a stair tile even though the path line pass through it. 

This will change token elevation: https://prnt.sc/19mplgi
This will not: https://prnt.sc/19mpyrt

The token visually simulate being on all of the points in the path, is there a way to check if there is a stair during this simulation?

**Comment by theripper93** [comment]
that is a system limitation and is the same with all modules of this kind, mlt behave the same, as does active auras and so on. Just be aware of it since every module that does polygon checking works that way
