### ISSUE TITLE
Changeing token heigth does not update visible tokens

### ISSUE THREAD

**Issue by Nordiii** [theripper93/Levels#3]
When you change the token heigth it wont update the visible tokens, your token needs to move for this to happen.

Foundry: 0.8.6
System: DnD5e 1.3.3
Server OS: Pi Buster (Debian)
Browser: Firefox
Modules: Better Roofs, Levels, libWrapper, Multilevel Tokens, Universal Battlemap Importer

**Comment by theripper93** [comment]
can you confirm that you are on the latest version? as i pushed 2 updates close together yesterday

**Comment by Nordiii** [comment]
I started a new docker instance this morning and downloaded every module for the first time shortly before posting this issue.

**Comment by theripper93** [comment]
should be fixed in latest update
