### ISSUE TITLE
Lose ability to select tile

### ISSUE THREAD

**Issue by curtisshipley** [theripper93/Levels#35]
I'm not sure what I've done wrong. I can reproducibly get into a situation when tiles are visible but I cannot select them to change their settings/delete them. Doesn't matter which level  I put them on or how I toggle foreground/background. I can see them and they have the grid over the top. I just cannot select them.

Steps to reproduce:

I have 4 levels: ground, 1st, 2nd and 3rd. 
If I select 1st (above ground)
Switch to the tile tool. Make sure the house,  the gate/wall and tree icons are not selected.
Place a new tile.
It is now immediately selectable. 
Double click on it, go to Overhead, check is overhead and update the token.
Now the tile will change visibility as expected as I go through the levels.
But now I can't select it.

**Comment by theripper93** [comment]
isn't it because you are in the bacground layer (house disabled) and you then put the tile into the overhead layer? (click House to make it selectable)
