### ISSUE TITLE
Console Error on Token Move

### ISSUE THREAD

**Issue by KonteiKeisei** [theripper93/Levels#37]
Receive the following console errors each time a token moves with only this module and its dependencies installed.

![image](https://user-images.githubusercontent.com/49371326/127380181-875c328e-8f47-4b03-a5bc-43dbc183463a.png)

Latest Foundry
Latest 5E SRD

**Comment by theripper93** [comment]
that does not look like a levels error, do you get it with no modules as well maybe?

**Comment by theripper93** [comment]
also do you notice anything happen? That error does not tell me anything unfortunatelly, it's basically an "unkown error"

**Comment by KonteiKeisei** [comment]
Small performance hiccups. Does not happen with no modules or on any other scene (without levels and those dependencies) I probably did something terribly wrong.

**Comment by theripper93** [comment]
not really sure what went wrong there gonna be honest, it seems a socket error of some kind but i'm not even sure how that could happen. If you want to pop into voice in my discord i'll try and figure it out, otherwise i'll close the issue, let me know

**Comment by KonteiKeisei** [comment]
I would be happy to work on it, though i am thinking it might be some issue with what i am doing.

That said, if you want to hop into a call/vtt and check it out, happy to get it sorted out even as just an FAQ

**Comment by KonteiKeisei** [comment]
I ended up deleting the scene and starting from scratch, seems to have resolved the error. Closing!
