### ISSUE TITLE
Measurement Controls always showing height 

### ISSUE THREAD

**Issue by rbl047** [theripper93/Levels#39]
![Screenshot_1](https://user-images.githubusercontent.com/46825122/127953620-d9658927-0b0f-4c6c-b6b5-43c5b2247ddc.png)
Whenever I draw a Measurement template, like a cone, circle and so on, a "0 ft" text appears above the icon. I found no way to hide that.

**Comment by theripper93** [comment]
Yep, that’s the elevation of the template

**Comment by rbl047** [comment]
> Yep, that’s the elevation of the template

Is there a way to hide that? I use those templates to make some visual effects on scenes. :)

**Comment by rbl047** [comment]
> no, but in the latest update if it's 0 it won't show anymore

HORAY!! Thanks =D
