### ISSUE TITLE
Overhead Tile Vision Fading

### ISSUE THREAD

**Issue by ducky00** [theripper93/Levels#4]
To be honest I don't know if it's a bug or not. In the showcase video it seemed to me that I can make an overhead tile disappear just where a token has vision, even when this token is not beeneath that overhead tile. I don't manage to pull this off. Could be a bug or no, but if not, I'd be gald if you could help me with the set up

**Comment by theripper93** [comment]
you can come over to the discord for this kind of issues, the invite is in the repo readme

**Comment by ducky00** [comment]
Nice, thanks for answering
