### ISSUE TITLE
Version 1.5.4 started counting "stairs height" with errors

### ISSUE THREAD

**Issue by rbl047** [theripper93/Levels#42]
After the 1.5.4 update it looks like the stairs drawing "height incrementor" started counting with error. 
May be its the a UI refresh problem? 
If I move the token very slow (using arrows keyboard ) the error do not occur. If I speed up a little bit, the error randomly returns. 
In my example, I went up a 20 ft. stairs, but it only counted 10 ft. 

![Screenshot_1](https://user-images.githubusercontent.com/46825122/128273705-4869a51c-c020-483c-a32a-48aeec5db8e6.png)

**Comment by theripper93** [comment]
i did not change anything in the stair logic, did you test with all mods disabled?

**Comment by theripper93** [comment]
also the stairs are not really intended to be used that way, you could have issues based on speed of connection by chaining them together like that, if you host locally you should be fine , but on stuff like forge you can have that kind of issue

**Comment by rbl047** [comment]
> i did not change anything in the stair logic, did you test with all mods disabled?

Nope. I've just updated Levels module. I will try to reproduce the error using only Levels Module and come back latter ;) Thanks!

**Comment by rbl047** [comment]
> also the stairs are not really intended to be used that way, you could have issues based on speed of connection by chaining them together like that, if you host locally you should be fine , but on stuff like forge you can have that kind of issue

I'm using "Levels" with "Wall Height" to give the tokens height and allowing them to see thought the walls. I will test with players latter to see if its ok. Thanks for the hint!

**Comment by rbl047** [comment]
I started using Multilevel token to do the job. Its different, but also works!

**Comment by theripper93** [comment]
ye whatever works
