### ISSUE TITLE
Tokens are being hidden by less obscurement than is normally required

### ISSUE THREAD

**Issue by DrYoshiyahu** [theripper93/Levels#47]
This module appears to be interferring with the amount of visibility one token needs to see another token, as I will demonstrate with the screenshots below.

Normally, this player token "Anastasia" should be able to see the dragon token with this much vision obstructed by walls. This screenshot was taken with no modules active.
![image](https://user-images.githubusercontent.com/14756430/131620557-7849ce63-f7db-4909-8daa-690ccdbb2b8e.png)

But with Levels (and its dependencies) enabled, the dragon token is hidden, from the same token's perspective. The polygon drawn on the map is only there to show where the dragon is supposed to appear. I confirmed that this issue occured without the polygon.
![image](https://user-images.githubusercontent.com/14756430/131620701-26f25fef-80fd-474d-aadc-077314b65b20.png)

I also confirmed that the vision works normally with the Better Roofs and Wall Height modules (but not Levels) enabled. This issue is unique to Levels.

Also, it's worth noting this map has no levels, rooves, or other module-specific features. The walls and windows are at default settings, and there are no tiles on the map at all.
![image](https://user-images.githubusercontent.com/14756430/131620823-388fc9ef-9d6d-4714-a2c8-ccd33abf56d5.png)
![image](https://user-images.githubusercontent.com/14756430/131620848-b90d30c7-5ae8-445a-8445-0cc70b0e1673.png)

**Comment by theripper93** [comment]
Enable precise token visibility in levels
