### ISSUE TITLE
Token Vision Sight

### ISSUE THREAD

**Issue by unrealkakeman89** [theripper93/Levels#48]
When Levels is activated and my tokens have a sight angle of 300, the sight vision is calculating the wrong rotational direction and causing my tokens to not be able to see to their immediate left. Please see the attached pictures for reference. 

I am running the SW5e system.
![Overhead View](https://user-images.githubusercontent.com/31608392/131735205-9936aeb7-6f43-4b85-a6db-ae0a468e9605.png)
![Example 4](https://user-images.githubusercontent.com/31608392/131735208-c304087d-5a48-462f-8789-82db64cb558f.png)
![Example 3](https://user-images.githubusercontent.com/31608392/131735209-5c325b1a-e16c-4b73-a528-84594f5e2e7c.png)
![Example 2](https://user-images.githubusercontent.com/31608392/131735210-d870bc81-ea82-4cfe-acf6-0e359d9f6122.png)
![Example 1](https://user-images.githubusercontent.com/31608392/131735213-563b5ec0-5bc4-416d-8867-3ccca60ad18d.png)

**Comment by theripper93** [comment]
fixed
