### ISSUE TITLE
Players can only see other tokens, when they have selected their token

### ISSUE THREAD

**Issue by marcstraube** [theripper93/Levels#5]
I have multiple tokens on the canvas, one of them a player token. All tokens are on the same level (height: 0).
The player can only see the other tokens, when they have selected their own token. As soon as the token is deselected, the other tokens are invisible.

Foundry: 0.8.6
Levels: 0.2.8

**Comment by theripper93** [comment]
it is intended behaviour, or multiple levels would show tokens you are not supposed to see

**Comment by marcstraube** [comment]
Would it be possible to make this a scene dependent setting? Or enable it only, when multiple levels are detected on the scene?

**Comment by marcstraube** [comment]
Sounds even better!

**Comment by theripper93** [comment]
I've pushed a new update, let me know how it looks now so i can close the issue

**Comment by theripper93** [comment]
i can't do much about the multiple selected tokens because it would be to heavy to compute, but at least now if you unselect all tokens you can have a clear view of what all your tokens see

**Comment by marcstraube** [comment]
As far as I was able to test, it seems to work. Logged in with GM and two player accounts on a simple map with just two walls. Players are able to see what I expected.

With "multiple selected tokens", do you mean the LoS for the selected tokens? I think the most GM's check it for the individual tokens anyway, so that should be ok.

Thanks for the fast fix!

**Comment by theripper93** [comment]
ye it only computes elevation for 1 selected token
