### ISSUE TITLE
Player vision not working correctly

### ISSUE THREAD

**Issue by 7thSim** [theripper93/Levels#51]
After the recent update I hadn't run any games, I did tonight and found that my players couldn't see many objects placed on the map, either as tokens or images. It was hit and miss - some could see some things and others couldn't see others. 
I pulled my various modules to get it so that players had vision and when I removed Levels it all worked (I kept the dependencies). 
Not sure why this is happening but it was a game killer.

**Comment by theripper93** [comment]
Haven’t heard if this issue, can you reproduce it if you enable it again?, where you using both levels and perfect vision?

**Comment by theripper93** [comment]
I say this because nothing changed about the visibility, the update was mostly on the deselection logic

**Comment by theripper93** [comment]
due to a single character typo, regular ovehead tiles where getting hidden in the last update (very unfortunate timing on the update since it was up for 8 hours) sorry for the inconvinience, this should now be fixed

**Comment by 7thSim** [comment]
thank you, it's working fine again. Oh, and I don't use perfect vision.

**Comment by theripper93** [comment]
very sorry for your game, sometimes i need to refactor to make things better and it's very hard to test all the things that can go wrong on my end, glad it's fixed
