### ISSUE TITLE
No changelog or commit messages are available

### ISSUE THREAD

**Issue by Varriount** [theripper93/Levels#53]
From a programming perspective, It would be very helpful if commit messages could be used to log the changes made to the module's code. I'm currently trying to figure out if some behavior I'm seeing is intended or not, but due to the lack of informative commit messages, it's difficult to know *why* a particular piece of code was written a certain way.

Additionally, from a user perspective, changelogs (which can be generated from commit messages) are helpful indicators in knowing whether updating a module will fix a severe bug. If an update doesn't fix a bug, a user might decide to postpone updating until they have time to test that the update doesn't break anything.

**Comment by theripper93** [comment]
I have changelogs in my discord server and I’m not writing commit messages

**Comment by Varriount** [comment]
Why not? And what is the link to your Discord server? Could you put it in the README so that users know how to get it?

**Comment by theripper93** [comment]
The link is the first thing in the readme

**Comment by Varriount** [comment]
Ah, ok. Thanks! I had missed it among all the other buttons.
