### ISSUE TITLE
Changing a token's height doesn't hide all previously visible tokens

### ISSUE THREAD

**Issue by Varriount** [theripper93/Levels#54]
When a player token's height is changed, the player's client doesn't seem to always "remove" tokens that are no longer visible. Oddly, this doesn't seem to occur on the GM's client.

Here is a token on the second level of a map:
![image](https://user-images.githubusercontent.com/524596/133918636-e39b6d04-b63b-4c3d-b613-c6f0552d39cd.png)

When the token's height is changed by either the GM or the player, the player sees this:
![image](https://user-images.githubusercontent.com/524596/133918672-e3e1dc88-8728-4d2a-ba1c-9906d14828d9.png)

(I enabled the LOS debug flag to see what the sight calculation was returning. This occurs even with the LOS debug flag disabled)

If the player refreshes their client, or attempts to select the "ghost" token, then the token's vision usually fixes itself.

**Comment by theripper93** [comment]
Does the player have ownership or observer over that token? Does is happen only on the specific token? I see that the one on the right is fine. Is it a position thing?

**Comment by Varriount** [comment]
The player has "Observer" permissions on the token. Changing the permissions to "Limited" or "None" seems to work around that particular problem, but then the "inverse" seems to occur: when the player token's height is changed to be on the same level as the observer token, the observer token isn't rendered:
![image](https://user-images.githubusercontent.com/524596/133943555-a5ea5ae5-5348-43e6-a74d-2d6752077d20.png)

**Comment by theripper93** [comment]
could you veryfy with all other mods disabled, and if you can reproduce this on a fresh scene?

**Comment by Varriount** [comment]
Very strange. After disabling all other mods and creating a new scene, player clients don't seem to be able to load any scenes other than the initial (active) scene. Switching to another scene (either by having the player client navigate there, or by having the GM pull a player to the scene) causes some sort of loading error:
```
18:00:03.535 Uncaught (in promise) TypeError: setting getter-only property "filters"
[Detected 1 package: lib-wrapper]
    destroy display.min.js:8
    destroy display.min.js:8
    destroy sprite.min.js:8
    destroy display.min.js:8
    tearDown foundry.js:18630
    tearDown foundry.js:18630
    tearDown foundry.js:19749
    tearDown foundry.js:38766
    tearDown foundry.js:17599
    draw foundry.js:17622
    view foundry.js:15619
    _onClickScene foundry.js:29063
    jQuery 9
    activateListeners foundry.js:28967
    _render foundry.js:2077
    call_wrapped libWrapper-wrapper.js:467
    <anonymous> listeners.js:111
    _render#0 libWrapper-wrapper.js:162
    _render foundry.js:28871
    render foundry.js:2011
    render foundry.js:28864
    broadcastActivity foundry.js:17154
    _initialize foundry.js:17759
    draw foundry.js:17689
    view foundry.js:15619
    initializeCanvas foundry.js:4514
    setupGame foundry.js:4388
    _initializeGameView foundry.js:5213
    _initializeView foundry.js:5189
    initialize foundry.js:4286
    call_wrapped libWrapper-wrapper.js:467
    libWrapperInit libWrapper-api.js:696
    initialize#0 libWrapper-wrapper.js:162
    <anonymous> foundry.js:53613
    async* foundry.js:53595
display.min.js:8:7352
```

**Comment by theripper93** [comment]
ok, this is getting just more cofusing, would you mind coming into the discord and screenshare for me?
