### ISSUE TITLE
conflict with update tiles

### ISSUE THREAD

**Issue by rinnocenti** [theripper93/Levels#55]
whenever another script updates a tile, that tile is placed over the character (even the index at 0 or the map has no levels) and sends an error

https://user-images.githubusercontent.com/3178127/133941980-5bb27a80-6fd7-404b-ad6a-41aede74397e.mp4

i did a test using monk's tile trigger but if i do tile.update{hidden: false/true} the error happens too.

![image](https://user-images.githubusercontent.com/3178127/133942034-ca768a9b-f3a6-4274-a9f8-7c79a5d26e8a.png)

**Comment by theripper93** [comment]
well spotted, it's a function i removed but forgot that reference, fix incoming
