### ISSUE TITLE
Hole not working for token on higher elevation

### ISSUE THREAD

**Issue by vanderleitelesjr** [theripper93/Levels#6]
Enabled the new hole settings, but still when there is a token standing on a higher elevation it cannot see the lower token standing in the hole. (weirdly enough the health bar and the elevation (15 ft) can still be seen)

![image](https://user-images.githubusercontent.com/40318093/121449114-82ec2900-c96f-11eb-91a4-0ce54ef99f34.png)

It does work the other way around, a token in a lower elevation can see the one standing above it in a hole area. 

![image](https://user-images.githubusercontent.com/40318093/121449269-d6f70d80-c96f-11eb-8b05-21bcfc00a4c1.png)

**Comment by vanderleitelesjr** [comment]
Unless I am doing something really stupid when setting the hole areas

**Comment by theripper93** [comment]
would you mind comin in my discord so i can have a look via screen share? https://discord.gg/F53gBjR97G

**Comment by theripper93** [comment]
tile needed transparency to look through it - issue closed
