### ISSUE TITLE
Tokens can see through tiles

### ISSUE THREAD

**Issue by kaidauart** [theripper93/Levels#65]
For some reason, my tokens are able to see through tiles to look at tokens on other floors. Fiddling with the Z-index setting fixes it temporarily, but the issue comes back after reloading the page.

![sfsfdsfsd](https://user-images.githubusercontent.com/81168210/142591161-fe1be5e4-6b5e-4939-8aaa-2cd1e8559dc8.JPG)
![dfdfdfs](https://user-images.githubusercontent.com/81168210/142591195-73bf272d-136d-42f5-b22f-fd72a048daed.JPG)
![sfdsfd](https://user-images.githubusercontent.com/81168210/142591227-ab08466d-7106-45fd-b95c-3d1c9a1a565a.JPG)
![sdfsdf](https://user-images.githubusercontent.com/81168210/142591246-87dc75e4-4a13-4c0d-8934-5d8a868c6a73.JPG)

**Comment by theripper93** [comment]
The height of your token is probably incorrect, or you have a hole - if this dies not solve it use the discord channel for further troubleshooting
