### ISSUE TITLE
Problems with System Update and Decimal Elevation

### ISSUE THREAD

**Issue by rinnocenti** [theripper93/Levels#66]
I know you are upgrading to v9. however with the update of the D&D system and the elevation of the tokens now accepting decimal values in version 0.8.9.
the levels ended up having visualization problems for example if the token is in 0.0 and the other in 0 one does not see the other.

**Comment by theripper93** [comment]
That is defiinately not the case, the elevation of tokens always acceppted decimals and levels always supported it, did you check with all other mods disabled?

**Comment by theripper93** [comment]
Cannot reproduce - no followup - closed
