### ISSUE TITLE
Update fails due to ver. 9

### ISSUE THREAD

**Issue by crogonint** [theripper93/Levels#67]

**Comment by crogonint** [comment]
In FoundryVTT, when updating Add-on modules, Levels reports that it can't update because it requires core software version 9.

..I'm not sure if this is expected behavior or not. I've been following your discussion on the Discord version 9 channel.. you are truly a blessing to the community. :)

**Comment by theripper93** [comment]
Yes it is expected, some of my modules are already ready for v9 that's why it does not let you update :)
