### ISSUE TITLE
Changing levels through the UI not working

### ISSUE THREAD

**Issue by yorkshirelandscape** [theripper93/Levels#7]
Foundry ver. 0.8.6
Levels ver. 0.5
Pathfinder2e ver. 2.1.1.6052
Chrome ver. 91.0.4472.77

Nothing I do seems to affect which level is active. Clicking the up or down buttons or selecting the level in the Levels HUD has no effect (except that sometimes a tile which is visible may cease to be so if you press up or down). A created tile still receives the top and bottom heights specified in the active level (according to the HUD). However, after the first one you create, setting any subsequent tiles as Overhead causes them to disappear, even if you have Foreground view enabled. They can't be selected and don't seem to exist until you disable the module. I'm not sure whether these are related issues or not.

**Comment by theripper93** [comment]
i would want to check this as well via discord

**Comment by Koalahund** [comment]
same problem here, no errors in console

**Comment by theripper93** [comment]
did you try with the latest update?

**Comment by theripper93** [comment]
should be fixed in 0.5.4
