### ISSUE TITLE
levels is hiding Tokens that are out of sight, Player controlled, and Party Vision is enabled

### ISSUE THREAD

**Issue by galaara98** [theripper93/Levels#72]
if Pf2e "Shared Party Vision" is enabled (Configure > System Settings > Limit Metagame Information > Shared Party Vision)  and Levels is installed and enabled
a PC controlled token (thing we want to see) that is out of line of sight from another PC controlled token (thing the player is selecting, controlling etc.), then the first token disappears.

when levels is disabled, the expected result happens of the token is still visible.

Foundry: 9.238
PF2e: 3.1.3.9639
Levels: 2.3.6

Issue exists even if Levels is the only mod enabled (incl dependencies, wall height, better roof, and libwrapper)
Issue does not exist if Only wall height, better roof and libwrapper are enabled

**Comment by theripper93** [comment]
Levels overrides completely the token visibility, so it's expected that anything else that touches it will cause incompatibilites. Levels has APIs to hook in and insert your own vision logic - if you want to bring PF2 devs into the conversiation i can walk them trough on how to integrate.

**Comment by theripper93** [comment]
Since the PF2e system is not willing to add module compatibility, and i'm not willing to add System specific compatibility, i'll simply add it in the list of conflicts on the repository.
