### ISSUE TITLE
Wall block light regardless of height

### ISSUE THREAD

**Issue by BladeFireLight** [theripper93/Levels#73]
Walls that block only  light ignore height setting and block light above or below

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

On a side note, I think this is a wall height issue, try without levels and consider reporting in the appropriate repository
