### ISSUE TITLE
Lights sources are sometimes rendered from the perspective of the previously selected token

### ISSUE THREAD

**Issue by strongpauly** [theripper93/Levels#74]
**ALL OTHER MODULES DISABLED?** false - requires Wall Height for bug to be seen
**Module:** Levels 2.4.3
**Conflicting Module **: N/A
**Foundry and System version**: Foundry 9.242 DnD5e 1.5.6
**OS, Hosting, Browser **:  Seen on MacOS Electron, and Chrome Ubuntu Linux Hosted
**Short Description of bug**:
When changing token selection light sources are rendered incorrectly apparently using the height setting of the previously selected token.
**Simple steps to reproduce the bug**:

1. Create a wall with height from top -1, bottom -10.
2. Place a light source with no height limits behind the wall.
3. Place a token (Token A) with vision on the opposite side of the wall, with elevation -10.
4. Place a second token (Token B) with vision on the same side (with the wall in between them and the light), but with elevation 0.
5. Select Token A - scene is rendered with the wall blocking the light.
6. Select Token B - scene is still rendered with the wall blocking the light.

Expected Result:
Scene should be rendered from the perspective of Token B.  This can be seen by deselecting Token B, then re-selecting it.

**Screenshots and/or console errors**:

https://user-images.githubusercontent.com/853954/148645232-57ceba85-cb8f-49ca-9670-656e64da5071.mov

**Comment by theripper93** [comment]
Can you confirm this is not just a wall height issue and nit a levels one?

**Comment by strongpauly** [comment]
Perhaps it is a WallHeight issue, but without Levels enabled it renders the light incorrectly until its moved.  The behaviour is slightly different with Levels enabled as described above.

**Comment by theripper93** [comment]
ye, then the core issue is on wallheight side, i would suggest opening an issue there since i can't to much on my end

**Comment by strongpauly** [comment]
I've created an issue with that module here: https://github.com/erithtotl/wall-height/issues/45
