### ISSUE TITLE
how do you check a PC is a PC?

### ISSUE THREAD

**Issue by evisanzay** [theripper93/Levels#76]
More than a issue this is a question. I´m trying to get "spot player" working in my custom system and I would like to have some insight in how the check is done (if it´s a property or something) to replicate that property in my system.

Regards!

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
