### ISSUE TITLE
Possible to work with levels < 10 ?

### ISSUE THREAD

**Issue by Endoril** [theripper93/Levels#77]
Hi,

It's seems that the module dont work correctly if i set levels with height < 10, for exemple:

Floor: 3 5
Ground level : 0 2
Underground: -3 -1
-> and same values to tiles associated with theses levels 

Am i doing something wrong, or it is normal behavior ?

If it is normal, there is no problem when using feets, but in meters, having level of 10m is not very accurate.

Thanks for your answer !

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
