### ISSUE TITLE
Small and non integer level height not working correctly

### ISSUE THREAD

**Issue by wush3** [theripper93/Levels#78]
**ALL OTHER MODULES DISABLED?** true
**Module:** Levels 2.4.9

**Foundry and System version**: eg. Foundry 9 build 245  SWADE 0.22.5 ( not game system related)
**Windows 11 Pro 

When level heights are set to small non integer values (tested with 0-1.9 , 2-3.9 and token sight height set to 1.8)  upper level walls block vision on lower levels. It is not totaly consistent.

Also normal walls don't block movement anymore unless fence option is set. 
Some game systems require small scale because the way movement works in them (for example savage worlds)

**Comment by theripper93** [comment]
answered in discord (i think) if not, wall height handles that part, not levels.
