### ISSUE TITLE
Foundry Server Debug Log shows warning...

### ISSUE THREAD

**Issue by karpana** [theripper93/Levels#79]
When I restart my Foundry instance, this message is continually present in the `debug.log` file.

Foundry Version: v9 build 249
System: PF1
Host/Server Operating System: Raspberry Pi 4.

```
{"level":"warn","message":"Package levels contains 2 compendium definitions that still use the deprecated 'entity' field instead of 'type'.","timestamp":"2022-02-07 09:18:04"}
```

**Comment by theripper93** [comment]
Thanks for the report, i've updated it to the new definition, i will be correct in the next update i push - that said you can ignore it it will be fine until v10
