### ISSUE TITLE
Disabling the module may cause some tiles to disappear

### ISSUE THREAD

**Issue by yorkshirelandscape** [theripper93/Levels#8]
Foundry ver. 0.8.6
Levels ver. 0.5
Pathfinder 2e ver. 2.1.1.6052
Chrome ver. 91.0.4472.77

Disabling the module may cause some tiles to disappear. I haven't noticed any rhyme or reason as to which or why.

**Comment by theripper93** [comment]
do they reappear after a refresh?, are they there but invisible? do they get deleted? i don't see how that can happen to be honest

**Comment by theripper93** [comment]
seems to be a foundry related issue possibly - the module doesen't create or destroy tiles
