### ISSUE TITLE
Fog being full black while selecting a token with vision

### ISSUE THREAD

**Issue by uniwars** [theripper93/Levels#82]
Hello, I got a bug while making a scene with levels that makes all non-directly in line of sight things being in a black fog.

Normal behavior : 
![image](https://user-images.githubusercontent.com/65986545/159117850-d787c599-8d57-4d1e-96fa-003b4ab47335.png)

Now : 
![image](https://user-images.githubusercontent.com/65986545/159117865-8d27ea45-d12c-48e9-80db-6e65f3b37fd5.png)

If there is no levels on the scene it works fine, if levels module is disabled it wokrs also fine.
I tried enabling/disabling fog of war on scene, adding/removing view limit, resetting fog of wa and uninstalling/installing the module.

I disactivated all modules but levels and the problem is still here, all with all modules activated but levels the problem is gone.

The normal behavior only works if I have the levels UI enabled, selecting the correct level, then selecting a token. There I will see as intended, but the moment I deselect/select the token again it no longer works and I have to re-select the level in the UI, then the token.

the last thing I remember doing before the problem appeared was to set a view limit on a token because I was trying to understand why my roof appeared correctly only from  2 side out of 4

I have 3 servers that share modules, modules and player's settings and the problem is on all my server.

If it can help I can give you GM access to my server.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
