### ISSUE TITLE
Fog of war stops working correctly on a specific level

### ISSUE THREAD

**Issue by NdranC** [theripper93/Levels#83]
**ALL OTHER MODULES DISABLED?** 
[True enough](https://i.imgur.com/6YkkLZi.png)

**Module:**
Levels 2.7.1

**Foundry and System version**:
Foundry v9 Build 255, DnD5e 1.5.7

**OS, Hosting, Browser (if applicable)**:
Tested on Firefox and Brave

**Short Description of bug**:
[Video Showcasing the Problem](https://youtu.be/VszPlpVpXxc)

Basically if a token roams in both basements nothing is wrong. But the moment they leave to the ground floor and come back, the first basement is completely fine but the lower one presents 2 issues:

1. The fog of war has been cleared for a big portion of the level. It seems to be a fog of war that is an amalgamation of the upper levels.
2. The fog of war is no longer the "levels advanced fog of war" which is always black and has no memory of where you have been but it now behaves like normal vanilla foundry fog.

**Simple steps to reproduce the bug**:
[Replicating Bug on a New World](https://youtu.be/ASh_ljYl2wM)

1. Create a new world and enable the mods shown in the screenshot
2. Create a new scene with a map
3. Create 3 levels, Lower Dungeon (-20, -11), Upper Dungeon (-10, -1), Ground Floor (0, 9)
4. Wall Lower Dungeon with correct height making sure there are areas the token can't see behind them
5. Import a map in the overhead layer for Upper Dungeon and Ground Floor as well as wall them
6. Mark the Upper Dungeon Map Tile as "basement"
7. Make stairs that force the players to walk around to reach them
8. Navigating Upper Dungeon or Ground floor with a token with 120 dim vision causes the fog of war to be revealed and remember on the Lower Dungeon map

Alternative
5. Also import the Lower Dungeon as a overhead tile at the correct height
...
8. Same effect but this time the fog only gets revealed if the token explores the Ground Floor level

**Screenshots and/or console errors**:
[Errors on a new world](https://i.imgur.com/1554gKC.png)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

**Comment by NdranC** [comment]
I updated the main comment. Hopefully to the specifications required. Thanks for reopening it.

**Comment by NdranC** [comment]
I just wanted to add that I managed to circumvent this issue (so far) by creating another level under the lower basement called "Background". This seem to only happen to the level at the lowest available height. Performance is still pretty bad though.

**Comment by theripper93** [comment]
Should be fixed, please let me know if it's not the case and i'll reopen the issue
