### ISSUE TITLE
Massive lag spikes after update

### ISSUE THREAD

**Issue by NdranC** [theripper93/Levels#84]
**ALL OTHER MODULES DISABLED?**
[True enough](https://i.imgur.com/6YkkLZi.png)

**Module:**
Levels 2.7.1

**Foundry and System version**:
Foundry v9 Build 255, DnD5e 1.5.7

**OS, Hosting, Browser (if applicable)**:
Tested on Firefox and Brave

**Short Description of bug**:
Basically, I'm noticing a lot worse performance with the updated versions of wall height + levels + better roofs. Unsure as to which one is causing it. I had a scene with over 1600 walls, 2 basements and 4 floors and I had no noticeable slowdowns before. Walls create instantly but take seconds to move or they move instantly but there is a 6+ seconds lag spike after moving. Deleting a floor tile, placing one, resetting the fog of war, and loading the scene have several seconds of lag spikes after the action is normally completed.

I remade the scene with only 600 walls and I still have the same issues, but maybe slightly less longer spikes.

**Simple steps to reproduce the bug**:
Honestly, a complex scene with multiple floors and walls seems to be all it takes. Moving walls after placing them seems to be a great way to proc it.

1. Create a wall in a complex scene
2. Grab the edge of that wall and move it/drop it somewhere else
3. Immediately hold right click and try to pan the camera around, the entire UI should be unresponsive while the lag happens

**Screenshots and/or console errors**:
No noticeable errors while it's happening

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

**Comment by theripper93** [comment]
Since this seems to be a big I’ll make an exception and reopen the issue - before I can look anymore into it follow the readme  I linked above

**Comment by theripper93** [comment]
Update wallheight to 4.2.3 - the issue should be fixed
