### ISSUE TITLE
Defining the polygon manually

### ISSUE THREAD

**Issue by astefan16** [theripper93/Levels#85]
Hello, I wanted to request the capability of defining the polygon manually.

Instead of selecting which walls it should and which walls it shouldn't use automatically, I would want to be able to just draw the polygon myself.

My maps can get really complicated with a lot of overlapping walls (and messy)

I am not sure if this is possible but please tell me if it isn't.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

**Comment by astefan16** [comment]
Oh damn my bad

**Comment by astefan16** [comment]
> Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

Oh my bad, I will check the discord
