### ISSUE TITLE
LOS not calculating properly

### ISSUE THREAD

**Issue by slcao2** [theripper93/Levels#87]
When calculating LOS between tokens on different levels, it seems to be undercalculating what the token can see. All the token heights are set to be auto-calculated and I have not modified their height of them on the tokens.
The wall on the first floor seems to be blocking the sight from the second floor.
The following scenarios occur:
- When 1st floor wall height is set to bottom 0, top 39, what is shown in the pictures is happening (unable to see the 2 creatures on the 1st floor).
- When 1st floor wall height is set to bottom 0, top 30, then the token on the 2nd floor is able to see the 2 creatures on the 1st floor. 

This doesn't seem to be right, since the wall below the token is only up to 39 and the token vision from the 2nd floor I assume is going from about 46 counting in the height of the token. Even setting token height manually to 6 yields the same result.

I'm not sure if I'm missing some settings, if I'm not understanding the LOS rays correctly, or if it's genuinely a bug but from what I can tell from Baileywiki's tutorial videos, it should be able to see the targets. Let me know if you need any more information.

1st Floor
![image](https://user-images.githubusercontent.com/6742426/163546733-fed1a960-7e7b-43c0-bdd4-ddd8c294a619.png)
2nd Floor
![image](https://user-images.githubusercontent.com/6742426/163546689-8815e79d-6baa-4219-afd1-c8e17bf4f3df.png)

Module Settings
![image](https://user-images.githubusercontent.com/6742426/163546769-748986e7-0a06-4705-b21c-2d2855af8628.png)
![image](https://user-images.githubusercontent.com/6742426/163546626-18cc77ee-8a1a-4b94-8773-0e60ab4e0665.png)

### Version Information (latest versions of everything at the time of writing)
Foundry: 9.266
PF2E: 3.8.4.11118
Levels: 2.7.2
Wall Height: 4.2.7
All other modules not required by Levels have been disabled.

**Comment by slcao2** [comment]
Just read the ISSUE.md 🤦 Will close and properly format/ask on discord.

**Comment by theripper93** [comment]
Oh you can post issues here no problem but we can get it solved faster on discord, I’ll reach out there
