### ISSUE TITLE
Journal Entries on Canvas become unclickable.

### ISSUE THREAD

**Issue by Deadlander** [theripper93/Levels#88]
After placing journal entries onto my map, when I go to click on them with the layer tool active, they disappear and are replaced with the elevation pop-up, which disappears as well.  This only happens with Journal Entries which have layers placed above them. See attached video

https://user-images.githubusercontent.com/13036735/166080981-61f2bc14-96de-41cf-af1e-ccc7292438ff.mp4

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
