### ISSUE TITLE
[Feature Request] Add "Excluded Walls" field in the Overhead tab for tiles when defining a Polygon

### ISSUE THREAD

**Issue by That-Italian-Guy** [theripper93/Levels#90]
Right now it is very unlikely that you can use click&drag to mass select walls when defining a Polygon - unless your wall structure is extremely easy (IE: only external walls); but in that case you probably don't need to use the Define Polygon function to begin with.

A simple solution would be to allow to mass remove walls from the Polygon.

This is a quick mockup of the interface:
- Step 1: Clik+Drag to mass select **all** the walls. These go into the "Selected Walls" field:
![Untitled-1](https://user-images.githubusercontent.com/106380880/172044664-c8568184-24ec-4ce2-a9e5-997cf83d5e26.jpg)

- Step 2: Click+Drag to mass select the **walls to be removed** from the previous selection:
![Untitled-2](https://user-images.githubusercontent.com/106380880/172044684-eeeb1e57-9ac7-40b4-a9e3-19b2464a2ed6.jpg)

Selected Walls - Excluded Walls = Polygon.

I currently use a spreadsheet to do the same, but it would be nice to be able to do so directly from the interface.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
