### ISSUE TITLE
gm left click empty space to release a selected token collapses gm's levels view

### ISSUE THREAD

**Issue by modzy2** [theripper93/Levels#91]
if the GM is viewing a specific level, and has a token selected, with the 'left click to release' global setting on, when gm left clicks and empty space to de-select the token, the gm's view collapses to default and no longer viewing the single level.

**Comment by theripper93** [comment]
V10 is upon us and I’m basically gonna have to rewrite levels, so, not gonna bother to fix this since it’s deeply nested in levels logic im afraid
