### ISSUE TITLE
Question on creating a drawing on a roof

### ISSUE THREAD

**Issue by mjeffw** [theripper93/Levels#93]
This is more of a question than an issue.

I want to use the Foundry drawing tools to draw on the roof of a structure built with levels. I have a one story building where the ground floor is 0-9', which makes the roof 10'-Infinity.

I've tried creating a drawing and manually setting the Top and Bottom elevation to 10-Infinity, but the drawing just doesn't show on the scene. 

Any hints?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
