### ISSUE TITLE
Error with 10.278

### ISSUE THREAD

**Issue by jasharen** [theripper93/Levels#95]
Updated to the test version 10.278 and running into the following error:

File lightMaskingHandler.js

Line 123:
if(!light.coloration.uniforms) continue;

Uncaught TypeError: Cannot read properties of undefined(reading 'uniforms')

Any help would be appreciated :)

Cheers,
Jared

**Comment by theripper93** [comment]
I might had not published the latest update, try updating and let me know if it's fixed
