### ISSUE TITLE
Levels and stream module

### ISSUE THREAD

**Issue by slyandsmart** [theripper93/Levels#96]
Hi i use froundry 9 (269) as well as levels 2.8.9.2 and stramview 0.4.4.
But i can not see the any token on a deeper level inside the stream view browser.

Hope you can help me with this. 

Kind regards sly

**Comment by theripper93** [comment]
Stream view and Levels do not work together, levels requires a token selected. I've already discussed with the developer and there is no simple way to make them work together.
