### ISSUE TITLE
Forced dropping to set level.

### ISSUE THREAD

**Issue by MB1997** [theripper93/Levels#97]
I haven't found a way to "force" players to move a certain vertical distance in a one way fashion, like dropping down a hole or collapsing ground. 

I could imagine it to work like the Elevator but only 1 target layer and without a prompt.

Or to capture units that could fly or somehow stop themselves from falling, there could be a message like "You are about to fall to layer xyz. Want to try to stop falling?". The Gamemaster then gets a Prompt to stop the fall, by elevating the token to a level above the initial dropping layer.
 
Maybe a checkbox beneath "Levels Drawing Mode" or an additional option in the dropdown, like "Forced elevation".

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/#/faq/issues) and reopen the issue with all the relevant information.
